### PR TITLE
Add -v/--version, -h/--help description edit

### PR DESCRIPTION
**Pull request by huantianad**
Adds a -v/--version option, which shows pax's version. (Solves #63) The version is the same as the version in `pax.nimble`.\
Note: Currently only implemented in `spec`, not each subcommand, so will only work if used with no subcommand.

Rework -h/--help option, change help description for this option from "Show help message" to "show help message" to be consistent with other help descriptions.

### CODE REVIEW

**Comment by huantianad** [comment]
Not sure why CI is failing, could be because I'm testing on nim 1.6.2

**Comment by froehlichA** [comment]
No idea either why it thinks it's a void. Either way, I think reading the version from the latest git tag is a better method, as I don't need to manually keep the package version up-to-date.

**Comment by froehlichA** [comment]
Apologies for pushing directly to your pr, but would this work?

**Comment by huantianad** [comment]
Yeah that looks good! Only concern is building outside of a git repo clone, eg from GitHub release zips

**Pull request merged**
